env: local

local:
  log_level: DEBUG
  enableCompareLog: True
  app_name: app-shift-mgnt
  shift_category: ['ACC', 'GEN', 'OFF', 'LEAVE', 'HOLIDAY', 'NACC', 'EACC']
  shift_category_hours: ['ACC-HOURS', 'NACC-HOURS', 'EACC-HOURS', 'GEN-HOURS', 'TOTAL-HOURS']
  proj_dir: E:\\Sabs Learning\\resource_integrate
  app:
    cache_location: E:\\Sabs Learning\\resource_integrate\\cache\\
    user_cache_file: user.json
    shiftplan_cache_file: shift_plan.json
    team_members_cache_file: Team-Members.json
    team_years_cache_file: Team-Shift-Plan-Years.json
    download_excel: E:\\Sabs Learning\\resource_integrate\\frontend\\
    secret_key: bbe51d1c35fc70d801d63143b7363d7f
  templates:
    forbidden: errors/forbidden-403.html
    page_not_found: errors/page_not_found-404.html
    internal_server_error: errors/server_error-500.html
    home: home/home.html
    login: auth/login.html
    register: auth/register.html
    roaster_dash: dashborads/roasterDashboard.html
    shift_roaster: dashboards/shiftRoaster.html
    submit_roaster: dashboards/submitRoaster.html
    roaster_modal: modal/roasterModal.html
   
  log_path: E:\\Sabs Learning\\resource_integrate\\backend\\logs\\app-shift-mgnt.log
  logging:
    disable_existing_loggers: False
    version: 1
    formatters:
      simple:
        format: "%(asctime)s~%(pathname)s:%(lineno)d~%(funcName)s~%(levelname)s~%(message)s"
        
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
        
      file:
        filename: E:\\Sabs Learning\\resource_integrate\\backend\\logs\\app-shift-mgnt.log
        class: logging.handlers.RotatingFileHandler
        formatter: simple
        maxBytes: 10485760 #1024*2014*10=10 MB
        backupCount: 3
    loggers:
      shift-mgnt:
        level: INFO
        handlers: [console, file]
      clients:
        level: INFO
        handlers: [console, file]
        propagate: no
          
test:
  log_level: DEBUG
  enableCompareLog: True
  #app_name: 'app-shift-mgnt'
  shift_category: ['ACC', 'GEN', 'OFF', 'LEAVE', 'HOLIDAY'] 
  log_path: /ctoclogs/app-shift-mgnt.log #Mention your logging path
  logging:
    disable_existing_loggers: False
    version: 1
    formatters:
      simple:
        format: "%(asctime)s~%(pathname)s:%(lineno)d~%(funcName)s~%(levelname)s~%(message)s"
        
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
        
      file:
        filename: /ctoclogs/app-shift-mgnt/app-shift-mgnt.log
        class: logging.handlers.RotatingFileHandler
        formatter: simple
        maxBytes: 10485760 #1024*2014*10=10 MB
        backupCount: 3
      loggers:
        shift-mgmt:
          level: INFO
          handlers: [console, file]
        clients:
          level: INFO
          handlers: [console, file]
          propagate: no
          
prod:
  log_level: DEBUG
  enableCompareLog: True
  #app_name: 'app-shift-mgnt'
  shift_category: ['ACC', 'GEN', 'OFF', 'LEAVE', 'HOLIDAY'] 
  log_path: /ctoclogs/app-shift-mgnt.log #Mention your logging path
  logging:
    disable_existing_loggers: False
    version: 1
    formatters:
      simple:
        format: "%(asctime)s~%(pathname)s:%(lineno)d~%(funcName)s~%(levelname)s~%(message)s"  # Mention your logging style
        
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
        
      file:
        filename: /ctoclogs/app-shift-mgnt/app-shift-mgnt.log
        class: logging.handlers.RotatingFileHandler
        formatter: simple
        maxBytes: 10485760 #1024*2014*10=10 MB
        backupCount: 3
      loggers:
        shift-mgmt:
          level: INFO
          handlers: [console, file]
        clients:
          level: INFO
          handlers: [console, file]
          propagate: no
